package jasondecarvalho.snapshot.testing

import com.diffplug.selfie.Camera
import com.diffplug.selfie.CompoundLens
import com.diffplug.selfie.Selfie.expectSelfie
import com.diffplug.selfie.Snapshot
import com.vladsch.flexmark.html2md.converter.FlexmarkHtmlConverter
import org.http4k.core.Method.GET
import org.http4k.core.Request
import org.http4k.core.Response
import org.jsoup.Jsoup
import org.junit.jupiter.api.Test

class ExampleHtmlSnapshotTest {

    @Test
    fun `check html response`() {
        val response = app(Request(GET, "/snapshot-testing/html"))

        expectSelfie(response, responseCamera.withLens(htmlLens)).toMatchDisk()
//            .facet("status").toBe("200 OK")
            .facets("status", "md").toBe("""╔═ [status] ═╗
200 OK
╔═ [md] ═╗
Hello there!
============

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum congue quam, pretium tempor turpis sodales ac. Vivamus vulputate risus eget rhoncus ultrices. Phasellus magna odio, viverra vitae leo eget, congue dictum ligula. Nulla facilisi. Phasellus mollis, libero quis viverra placerat, lectus neque lobortis neque, a gravida nunc dolor in purus. Proin sem ipsum, ullamcorper quis commodo nec, finibus vitae est. Praesent nisl purus, dignissim vel libero vitae, laoreet vulputate nulla. Vestibulum neque nulla, suscipit sed nibh vel, elementum efficitur mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam in pellentesque risus. Donec mattis, sapien vitae pharetra eleifend, justo nisl vehicula sem, nec rhoncus enim ipsum ac metus. Aliquam erat volutpat. Praesent posuere augue eget mi finibus convallis. Nunc vel egestas ligula. Donec vitae purus bibendum, tincidunt tortor nec, volutpat odio. Phasellus elementum elit ligula, in suscipit urna scelerisque sit amet. Maecenas egestas mi malesuada sollicitudin posuere. Duis viverra sem ut tortor mattis tincidunt. Nunc nec rutrum libero. Nam porttitor nisl eget eros porta, non viverra felis consequat. Quisque ut ultricies quam. Duis porttitor tempus velit ac feugiat. Nunc facilisis magna sit amet augue sagittis imperdiet. Quisque malesuada diam eget pretium iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean placerat quam sit amet lacus varius bibendum. Maecenas in risus at erat ullamcorper accumsan vel vel nibh. Aenean varius condimentum sapien, eu accumsan turpis laoreet nec. Donec ac ultricies nisl. Duis non sapien quis ante venenatis cursus. Pellentesque cursus condimentum ullamcorper. Curabitur ut sem in neque bibendum egestas a id tortor. Ut id ante id augue interdum tempor vitae nec tellus. Nam a augue nibh. Fusce tincidunt nisl ut magna laoreet, eu varius erat auctor. Curabitur at dictum sapien. Aliquam nec eleifend erat. Vestibulum interdum nulla ut rutrum varius. Integer porttitor eget lorem non luctus. Phasellus quis erat condimentum, tempor nisl eu, volutpat odio. Quisque egestas ex at nisl dapibus tincidunt. Ut nec purus nec ante consequat bibendum a et tortor. Pellentesque a lobortis lacus. Vivamus non turpis elit. Mauris dignissim a ex at venenatis. Nunc eget tellus mi. Fusce eros nisi, aliquet ut tortor id, sodales ultricies ipsum. Phasellus imperdiet arcu vitae odio sagittis maximus. Donec a tortor convallis, aliquet odio sit amet, porta magna. Sed vestibulum ullamcorper luctus. Maecenas volutpat efficitur aliquam. Curabitur sed lacinia metus, dapibus dignissim erat. Phasellus urna metus, venenatis vitae hendrerit quis, consequat sit amet enim.
""")
    }

    private val responseCamera: Camera<Response> = Camera { response ->
        Snapshot.of(response.body.toString())
            .plusFacet("status", response.status.toString())
    }

    private val htmlLens = CompoundLens()
        .mutateFacet("", ::prettyPrintHtml)
        .setFacetFrom("md", "", ::htmlToMd)

    private fun prettyPrintHtml(html: String): String {
        val doc = Jsoup.parse(html)
        doc.outputSettings().prettyPrint(true)
        return doc.outerHtml()
    }
    
    private fun htmlToMd(html: String): String {
        return FlexmarkHtmlConverter.Builder().build().convert(html)
    }
}
